services:
  # The Web Service for Laravel
  - type: web
    name: sinina-co-web
    env: php
    buildCommand: composer install --no-dev && npm install && npm run build
    startCommand: php artisan migrate --force && apache2-foreground
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromContext: git.url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: sinina-co-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sinina-co-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: sinina-co-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: sinina-co-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sinina-co-db
          property: password
      - key: NODE_VERSION
        value: 20.x

databases:
  # The Managed PostgreSQL Database
  - name: sinina-co-db
    plan: free
    region: singapore # Adjust as needed
